# conf/bblayers.conf
#
# BitBake layers configuration for YCM4R1.
# This file is used when building WITHOUT kas.  Adjust BSPDIR to point at the
# directory that contains all cloned layers.

BSPDIR := "${@os.path.abspath(os.path.dirname(d.getVar('FILE', True)) + '/..')}"

BBPATH = "${TOPDIR}"

BBFILES ?= ""

BBLAYERS ?= " \
    ${BSPDIR}/poky/meta \
    ${BSPDIR}/poky/meta-poky \
    ${BSPDIR}/poky/meta-yocto-bsp \
    ${BSPDIR}/meta-openembedded/meta-oe \
    ${BSPDIR}/meta-openembedded/meta-python \
    ${BSPDIR}/meta-openembedded/meta-networking \
    ${BSPDIR}/meta-openembedded/meta-filesystems \
    ${BSPDIR}/meta-raspberrypi \
    ${BSPDIR}/meta-ros/meta-ros-common \
    ${BSPDIR}/meta-ros/meta-ros1 \
    ${BSPDIR}/meta-ros/meta-ros1-melodic \
    ${BSPDIR}/meta-ycm4r1 \
"
