# Layer configuration for meta-ycm4r1
# Compatible with Yocto warrior (2.7).

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
             ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "ycm4r1"
BBFILE_PATTERN_ycm4r1 = "^${LAYERDIR}/"
BBFILE_PRIORITY_ycm4r1 = "10"

# Declare compatibility with Yocto warrior core layer series.
LAYERSERIES_COMPAT_ycm4r1 = "warrior"

# Layers that must be present for this layer to work.
LAYERDEPENDS_ycm4r1 = "core \
                        openembedded-layer \
                        meta-python \
                        networking-layer \
                        meta-raspberrypi \
                        ros-common \
                        ros1 \
                        ros1-melodic"
