# Layer configuration for meta-ycm4r1
# Compatible with Yocto kirkstone (4.0).

BBPATH .= ":${LAYERDIR}"

BBFILES += "${LAYERDIR}/recipes-*/*/*.bb \
             ${LAYERDIR}/recipes-*/*/*.bbappend"

BBFILE_COLLECTIONS += "ycm4r1"
BBFILE_PATTERN:ycm4r1 = "^${LAYERDIR}/"
BBFILE_PRIORITY:ycm4r1 = "10"

# Declare compatibility with Yocto kirkstone core layer series.
LAYERSERIES_COMPAT:ycm4r1 = "kirkstone"

# Layers that must be present for this layer to work.
LAYERDEPENDS:ycm4r1 = "core \
                        openembedded-layer \
                        meta-python \
                        networking-layer \
                        meta-raspberrypi \
                        ros-common \
                        ros1 \
                        ros1-noetic"
